package Parking;

import java.sql.Timestamp;




    /**
     * Report.java
     * Represents a system report generated by admin
     * Matches the reports table in the database
     */
    public class Report {

        private int       reportId;
        private String    description;
        private Timestamp date;
        private String    generatedBy;

        // Constructor with ID (reading from database)
        public Report(int reportId, String description,
                      Timestamp date, String generatedBy) {
            this.reportId     = reportId;
            this.description  = description;
            this.date         = date;
            this.generatedBy  = generatedBy;
        }

        // Constructor without ID (creating new report)
        public Report(String description, String generatedBy) {
            this.description = description;
            this.generatedBy = generatedBy;
            this.date        = new Timestamp(System.currentTimeMillis());
        }

        // Getters
        public int       getReportId()    { return reportId;    }
        public String    getDescription() { return description; }
        public Timestamp getDate()        { return date;        }
        public String    getGeneratedBy() { return generatedBy; }

        // Setters
        public void setReportId   (int reportId)       { this.reportId    = reportId;    }
        public void setDescription(String description) { this.description = description; }
        public void setDate       (Timestamp date)     { this.date        = date;        }
        public void setGeneratedBy(String generatedBy) { this.generatedBy = generatedBy; }
    }


